Repository GetDKAN/dkan_starter, pull requests merged in 2018-10, with the labels that each got.

#515 Upgrade dkan to 1.15.5
  build-dkan.make
  dkan/dkan.info
  dkan/dkan.install
  dkan/drupal-org.make
  dkan/modules/contrib/facetapi/PATCHES.txt
  dkan/modules/contrib/facetapi/cross-site-scripting-facets-156778.patch
  dkan/modules/contrib/facetapi/plugins/facetapi/url_processor.inc
  dkan/modules/dkan/dkan_data_story/css/dkan_data_story.css
  dkan/modules/dkan/dkan_data_story/dkan_data_story.features.field_instance.inc
  dkan/modules/dkan/dkan_data_story/dkan_data_story.features.inc
  dkan/modules/dkan/dkan_data_story/dkan_data_story.info
  dkan/modules/dkan/dkan_data_story/dkan_data_story.views_default.inc
  dkan/modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.module
  dkan/modules/dkan/dkan_sitewide/dkan_sitewide.info
  dkan/modules/dkan/dkan_sitewide/modules/dkan_sitewide_search_db/dkan_sitewide_search_db.security.inc
  dkan/patches/cross-site-scripting-facets-156778.patch
  dkan/themes/nuboot_radix/assets/css/nuboot_radix.style.css
  dkan/themes/nuboot_radix/scss/components/_view.scss
Labels: In Progress

#513 Run cmds thr cmd prxy
  .ahoy/site/build.ahoy.yml
Labels: Code Review

#309 Updated docker documentation
  docs/common_tasks/setting-up-local-project.rst
  docs/docker-dev-env/installation.rst
  docs/getting_started/creating-a-new-project.md
Labels: Current Sprint
